"""Uttar Pradesh districts with their Hindi (and common alternative) names, so "बरेली" and "Bareilly" or
"Noida" and "Gautam Buddha Nagar" find the same District node. Keys are the English names used in the data."""

DISTRICT_ALIASES: dict[str, list[str]] = {
    "Agra": ["आगरा"],
    "Aligarh": ["अलीगढ़", "अलीगढ"],
    "Ambedkar Nagar": ["अंबेडकर नगर", "अम्बेडकर नगर", "अंबेडकरनगर"],
    "Amethi": ["अमेठी"],
    "Amroha": ["अमरोहा"],
    "Auraiya": ["औरैया"],
    "Ayodhya": ["अयोध्या", "Faizabad", "फैजाबाद"],
    "Azamgarh": ["आजमगढ़", "आजमगढ"],
    "Baghpat": ["बागपत"],
    "Bahraich": ["बहराइच"],
    "Ballia": ["बलिया"],
    "Balrampur": ["बलरामपुर"],
    "Banda": ["बांदा", "बाँदा"],
    "Barabanki": ["बाराबंकी"],
    "Bareilly": ["बरेली"],
    "Basti": ["बस्ती"],
    "Bhadohi": ["भदोही", "Sant Ravidas Nagar"],
    "Bijnor": ["बिजनौर"],
    "Budaun": ["बदायूं", "बदायूँ", "Badaun"],
    "Bulandshahr": ["बुलंदशहर"],
    "Chandauli": ["चंदौली"],
    "Chitrakoot": ["चित्रकूट"],
    "Deoria": ["देवरिया"],
    "Etah": ["एटा"],
    "Etawah": ["इटावा"],
    "Farrukhabad": ["फर्रुखाबाद"],
    "Fatehpur": ["फतेहपुर"],
    "Firozabad": ["फिरोजाबाद", "फ़िरोज़ाबाद"],
    "Gautam Buddha Nagar": ["गौतम बुद्ध नगर", "गौतमबुद्ध नगर", "गौतमबुद्धनगर", "Noida", "नोएडा", "Greater Noida",
                            "ग्रेटर नोएडा", "Gautambudh Nagar"],
    "Ghaziabad": ["गाजियाबाद", "गाज़ियाबाद"],
    "Ghazipur": ["गाजीपुर", "ग़ाज़ीपुर"],
    "Gonda": ["गोंडा"],
    "Gorakhpur": ["गोरखपुर"],
    "Hamirpur": ["हमीरपुर"],
    "Hapur": ["हापुड़", "हापुड"],
    "Hardoi": ["हरदोई"],
    "Hathras": ["हाथरस"],
    "Jalaun": ["जालौन", "Orai", "उरई"],
    "Jaunpur": ["जौनपुर"],
    "Jhansi": ["झांसी", "झाँसी"],
    "Kannauj": ["कन्नौज"],
    "Kanpur": ["कानपुर", "Kanpur Nagar", "कानपुर नगर"],
    "Kanpur Dehat": ["कानपुर देहात"],
    "Kasganj": ["कासगंज"],
    "Kaushambi": ["कौशांबी", "कौशाम्बी"],
    "Kushinagar": ["कुशीनगर"],
    "Lakhimpur Kheri": ["लखीमपुर खीरी", "लखीमपुर", "Lakhimpur", "Kheri", "खीरी"],
    "Lalitpur": ["ललितपुर"],
    "Lucknow": ["लखनऊ"],
    "Maharajganj": ["महराजगंज", "महाराजगंज"],
    "Mahoba": ["महोबा"],
    "Mainpuri": ["मैनपुरी"],
    "Mathura": ["मथुरा"],
    "Mau": ["मऊ"],
    "Meerut": ["मेरठ"],
    "Mirzapur": ["मिर्जापुर", "मिर्ज़ापुर"],
    "Moradabad": ["मुरादाबाद"],
    "Muzaffarnagar": ["मुजफ्फरनगर", "मुज़फ्फरनगर"],
    "Pilibhit": ["पीलीभीत"],
    "Pratapgarh": ["प्रतापगढ़", "प्रतापगढ"],
    "Prayagraj": ["प्रयागराज", "Allahabad", "इलाहाबाद"],
    "Raebareli": ["रायबरेली", "Rae Bareli"],
    "Rampur": ["रामपुर"],
    "Saharanpur": ["सहारनपुर"],
    "Sambhal": ["संभल"],
    "Sant Kabir Nagar": ["संत कबीर नगर", "संतकबीरनगर"],
    "Shahjahanpur": ["शाहजहांपुर", "शाहजहाँपुर"],
    "Shamli": ["शामली"],
    "Shravasti": ["श्रावस्ती"],
    "Siddharthnagar": ["सिद्धार्थनगर", "सिद्धार्थ नगर"],
    "Sitapur": ["सीतापुर"],
    "Sonbhadra": ["सोनभद्र"],
    "Sultanpur": ["सुल्तानपुर"],
    "Unnao": ["उन्नाव"],
    "Varanasi": ["वाराणसी", "Banaras", "बनारस", "Kashi", "काशी"],
}

# thana_matrix spells some district names differently from analyzed_data
DISTRICT_CANONICAL: dict[str, str] = {
    "gautambudh nagar": "Gautam Buddha Nagar",
    "kanpur nagar": "Kanpur",
    "kanpur outer": "Kanpur",
    "noida": "Gautam Buddha Nagar",
    "allahabad": "Prayagraj",
    "faizabad": "Ayodhya",
    "lakhimpur": "Lakhimpur Kheri",
    "kheri": "Lakhimpur Kheri",
    "badaun": "Budaun",
    "rae bareli": "Raebareli",
}
